#!/bin/bash
# 1.) Check permission on ~/.ssh directory
# 2.) Check permission on ~/.ssh/*_id.pub 
# 3.) Check permission on ~/.ssh/*_id
# 4.) Check permission on ~/.ssh/authorized_keys
# 5.) Make sure *_id.pub is in authorized_keys

#TODO What if multiple keys?
#TODO Exist later if 0 keys found (check directory permissions
#TODO Exist later if OK with multiple keys
#                                 2025-08-01 Kent Milfeld

  [[ $# != 1 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
  [[ $1 == t ]] && O=T
  [[ $1 == v ]] && O=V

space10='          ' tab=$space10
STATUS=0

i=0
pub_key_files=( id_ed25519.pub id_rsa.pub )

echo "SSH setup"

output=`ls $HOME/.ssh/*.pub`
if [[ $? != 0 ]]; then
  echo " Could not find any public key (of form \*pub)."
  exit 1
else   #determine key type
  for file in ${pub_key_files[@]}; do
    if [[ $output =~ $file  ]]; then
       pub_keys+=($file)
    fi
  done
fi
 if [[ ${#pub_keys[@]}  == 1 ]]; then
   if [[ $O == N ]] || [[ $O == V ]]; then
    echo "$tab Found public  key ${pub_keys[0]}" && pub_key=${pub_keys[0]}
   fi
   [[ $O == T ]]  && T_string="Found public key ${pub_keys[0]}"
 fi
 [[ ${#pub_keys[@]}  == 0 ]] && echo "$tab Found NO public key (searched: ${pub_key_files[@]})" && exit 1
#[[ ${#pub_keys[@]} -gt 1 ]] && echo " Found Multiple public key ${pub_keys[@]}." && exit 1

 pub_key=${pub_keys[0]}
priv_key=${pub_key%%.pub}

output=`ls $HOME/.ssh/$priv_key`
if [[ $? == 0 ]]; then
   [[ $O == N ]] || [[ $O == V ]] && 
     echo "$tab Found private key $priv_key"
   [[ $O == T ]] && 
     T_string="$T_string and private key $priv_key" 
else
  echo "$tab Could NOT find private key $priv_key."; exit 1
fi

filenames=( .ssh $priv_key $pub_key authorized_keys )
pathnames=( $HOME/.ssh $HOME/.ssh/$priv_key $HOME/.ssh/$pub_key $HOME/.ssh/authorized_keys )
 perms=(     drwx------ -rw-------           -rw-r--r--          -rw------- )
#perms=(     .rwx------ .rw-------           .rw-r--r--          .rw------- ) #tests
set_perms=( 700        600                  644                 600 )
 #echo ${pathnames[@]}
 #echo ${perms[@]}
 #echo ${set_perms[@]}
 #echo ==================================================


check_perm(){

  pathname=${CL_PATHNAME-$1} 
      perm=${CL_PERM-$2} 
   setperm=${CL_SETPERM-$1} 

  local O=$4
  return_status=0

  stat_perm=`stat -c %A ${pathnames[$i]}`
  status=$?
  
  name=`basename ${pathnames[$i]}`
  short_pathname=$(echo ${pathnames[$i]} | sed 's@'$HOME'@$HOME@')
 #echo short_pathname=$short_pathname
  
  
  if [[ $stat_perm == ${perms[$i]} ]]; then
    [[ $O == N ]] || [[ $O == V ]] &&
    printf "%s %-40s %s\n" "$tab" "Permissions correct for $name:" "${perms[$i]}"
  else
    return_status=1
    echo "$tab FAILED Permissions on $short_pathname are incorrect."
    echo "$tab   Found:     $stat_perm permissions for $name"
    echo "$tab   Should be: ${perms[$i]}"
    echo "$tab   Execute:   chmod ${set_perms[$i]} $short_pathname"
  fi

 #[[ $space == "" ]] && pass_space=$tab #first time no space
  space=$tab #first time no space

}

for i in ${!pathnames[@]}; do
   check_perm ${pathnames[$i]} ${perms[$i]} ${set_perms[$i]} $O
   [[ $return_status != 0 ]] && STATUS=$return_status
done

if [[ $O == T ]] && [[ $STATUS == 0 ]]; then
   echo "$tab $T_string" 
   echo "$tab Permissions OK for: ${filenames[@]}" 
fi

exit $STATUS
