#!/bin/bash


#TODO  warning isi project ending soon or near 5% limit
##TODO fail is 2 percent left

  [[ $# == 0 ]] && O=N    #Command line options T=terse,v=Verbose, default Normal
  [[ $1 =~ t ]] && O=T
  [[ $1 =~ v ]] && O=V
  [[ ! "$O" =~ [NTV] ]] && echo "USAGE: $0 [-t|-v] # terse|verbose output"

  STATUS=0

  HPC_OSs=(rocky centos fedora ubuntu debian)
  if [[ -f /etc/os-release ]]; then
    output=$( grep ^ID= /etc/os-release ) #e.g. ID="rocky"
    eval $output
    OS=$ID
    if [[ ! ${HPC_OSs[@]} =~ $OS ]]; then
       echo "internal ERROR: could not get OS from /etc/os-release"
       echo "  search list ( ${HPC_OSs[@]} )"
       exit 1
    fi
  else
    [[ `uname -a` =~ Darwin ]] && OS=darwin
  fi

  [[ $OS == darwin ]]          && opts='-s'
  [[ ${HPC_OSs[@]} =~ $OS   ]] && opts='-A'

  host_name=`hostname $opts`

  for sys in frontera vista stampede ls6; do
    [[ $host_name =~ $sys ]] && AT_TACC=yes TACC_SYS=$sys
  done

  [[ $AT_TACC != yes ]] && echo "ALLOCATIONS" && echo "NONE programmed for this systems." && exit 0

                  #milfeld:*:1117:825112:milfeld:/home1/00770/milfeld:/bin/bash
  user_info=`getent passwd $USER`
  IFS=":" read -ra usr_etc_pwd <<< "$user_info"  # put fields in /usr_etc_pwd array

  user=${usr_etc_pwd[0]}
   uid=${usr_etc_pwd[2]}
   gid=${usr_etc_pwd[3]}
  home=${usr_etc_pwd[5]}
  login_shell=${usr_etc_pwd[6]}

if [[ $AT_TACC == yes ]]; then
  TACC_ACC_DIR="/usr/local/etc/"
  [[ $sys == ls4 ]] && TACC_ACC_DIR=/sge_common/default/acct/map/
         proj_map=$TACC_ACC_DIR/project.map
     projuser_map=$TACC_ACC_DIR/projectuser.map
  projbalance_map=$TACC_ACC_DIR/projectbalance.map
        usage_map=$TACC_ACC_DIR/usage.map

  projects=( $(grep -E "^${user}\\b" $projuser_map) ) #projuser_map
  status=$?
  projects=("${projects[@]:1}")  #remove 1st element, user name
  if [[ $status == 0 ]]; then
    if [[ $O == V ]] ; then
      echo "PROJECTS found (IDs ${projects[@]}, repectively): "
    fi
  else
    echo "PROJECTS: NO PROJECTS FOUND."
    exit 1
  fi

# Project Details
  valid_count=0 expired_count=0
  for proj_id in ${projects[@]}; do
    name_id=( $(grep -E " $proj_id\\b" $proj_map) )  #$proj_map
    proj_name=${name_id[0]}

    
    usage_line=( $(grep -E "^$proj_name:" $usage_map) )  #$usage_map
    IFS=":" read -ra usage <<< "$usage_line"
    start_date=${usage[2]}
      end_date=${usage[3]}
      allocate=${usage[4]}
          used=${usage[5]}
       balance=${usage[6]}

    if [[ ${#usage[@]} -ne 7 ]]; then
        echo -e "WARNING: invalid account line for $proj_name:\n" \
                "         $usage_line"
                  #MCB22024:Vista:2022-04-26:2027-01-31:10000:3.496:9996.504
        STATUS=3
    else
      valid_count=$(( valid_count + 1 ))
      today=`date +%F`
      today_no=$(awk -F'-' '{printf("%4d%02d%02d\n",$1,$2,$3)}' <<< `date +%F`)
        end_no=$(awk -F'-' '{printf("%4d%02d%02d\n",$1,$2,$3)}' <<< $end_date)

      if [[ $today_no -gt $end_no ]]; then
        expired_count=$(( expired_count + 1 ))
        if [[ $O == V ]] ; then
          echo "EXPIRED: $proj_name expired $end_date"
        fi
        exp_proj+=($proj_name)
        EXP_proj_date+=("$proj_name $end_date ")
      else
        if [[ $O == V ]] ; then
          printf  "ACTIVE : %8s (SUs Alloc:Used:Bal:Exp) %8s %8.0f %8.0f %s \n" \
                  "$proj_name" "${allocate}" "${used}" "${balance}" "$end_date"
        fi
          PC_remain=$(bc   <<< "100*$balance/$allocate")
          balance=${balance%.*}
          act_proj+=( $proj_name:Bal=$balance)
          ACT_proj+=( $proj_name )
          ACT_proj_PCremain+=( "$proj_name ${PC_remain}% " )
          ACT_proj_bal_PCremain+=( "$proj_name $balance ${PC_remain}%" )
      fi
#exp_proj=(CCSC1234 abc1234)   #For testing
#EXP_proj_date=("CCSC1234 10/10/24"  "abc1234 9/9/23")
      if [[ $proj_id == ${projects[-1]} ]] && [[ $O == T ]] ; then   #las proj_id
         [[ ${#exp_proj[@]} -gt 0 ]] && EXP="Expired: (${exp_proj[@]})"
         [[ ${#act_proj[@]} -gt 0 ]] && ACT="(${ACT_proj_PCremain[@]} %remain)"
         [[ $valid_count    -gt 0 ]] &&
           echo "PROJECTS: $ACT $EXP" 
      fi
      if [[ $proj_id == ${projects[-1]} ]] && [[ $O == N ]] ; then   #las proj_id
        #[[ ${#exp_proj[@]} -gt 0 ]] && EXP="Expired: (${exp_proj[@]})"
         [[ ${#act_proj[@]} -gt 0 ]] || [[ ${#exp_proj[@]} -gt 0 ]] &&
         echo "PROJECTS: Active/Inactive  Balance(SUs), %Available"
         [[ ${#act_proj[@]} -gt 0 ]] &&
         echo "ACTIVE: ${ACT_proj_bal_PCremain[@]}"
         [[ ${#exp_proj[@]} -gt 0 ]] &&
         echo "EXPIRED: ${EXP_proj_date[@]}"
      fi

    fi
  done

  # FAIL if no accounts valable, WARN if some inactive/expired
  if [[ $valid_count -gt 0 ]]; then 
    if [[ $expired_count -eq $valid_count ]]; then
      echo -e "FAIL: All valid projects are expired.\n"   #FAILURE
      exit 1
    fi
    [[ $expired_count -gt 0 ]] && exit 3                   #WARNING
  fi

  exit 0

fi
